export const SET_CURRENT_WORKSPACE = 'SET_CURRENT_WORKSPACE';
export const CREATE_PROJECT_OF_WORKSPACE = 'CREATE_PROJECT_OF_WORKSPACE';
export const ARCHIVE_PROJECT = 'ARCHIVE_PROJECT';
export const UPDATE_DROP_SECTION = 'UPDATE_DROP_SECTION';
export const UPDATE_DROP_TASK = 'UPDATE_DROP_TASK';
export const ADD_SECTION = 'ADD_SECTION';
export const ADD_SECTION_LEFT_RIGHT = 'ADD_SECTION_LEFT_RIGHT';
export const EDIT_SECTION = 'EDIT_SECTION';
export const DELETE_SECTION = 'DELETE_SECTION';





