export const GET_ALL_PROJECT_API = 'GET_ALL_PROJECT_API';
export const SET_CURRENT_PROJECT = 'SET_CURRENT_PROJECT';


export const UPDATE_DROP_SECTION = 'UPDATE_DROP_SECTION';
export const UPDATE_DROP_TASK = 'UPDATE_DROP_TASK';
export const ADD_SECTION = 'ADD_SECTION';
export const EDIT_SECTION = 'EDIT_SECTION';
export const DELETE_SECTION = 'DELETE_SECTION';
export const ADD_SECTION_LEFT_RIGHT = 'ADD_SECTION_LEFT_RIGHT';











